### ISSUE TITLE
Anonymous bind

### ISSUE THREAD

**Issue by samba2** [kwart/ldap-server#3]
Hi, 

thanks for your work. I want to use the ldap-server for an integration test. In our scenario the real ldap server allows an anonymous bind. Any ideas how I can tweak the ApacheDS to also allow anonymous binds?

This is what currently happens:
`$ ldapsearch -v -x -H ldap://localhost:10389 
ldap_initialize( ldap://localhost:10389/??base )
ldap_bind: Invalid credentials (49)
	additional info: INVALID_CREDENTIALS: Bind failed: ERR_229 Cannot authenticate user 
`

**Comment by kwart** [comment]
The `-a` argument was added to support anonymous bind.
