### ISSUE TITLE
Ldap server on Db

### ISSUE THREAD

**Issue by arvit1** [kwart/ldap-server#8]
Sorry for writing this request as an issue but I don't know were to write it. 

I would want to have the same ldap server but not an in memory one but with the default db (which I think is BerkleyDB) 

Thank you 
Arvit

**Comment by kwart** [comment]
I'm sorry, this project is aimed to simple in-memory instance. If you need your data persisted use directly ApacheDS or some other LDAP server (OpenDS/OpenDJ, ...).
