### ISSUE TITLE
groupOfUniqueMembers does not exist

### ISSUE THREAD

**Issue by mjpirez** [kwart/ldap-server#9]
Hi, first thanks for the util, it is very helpfull.

When I try to supply a ldif with groupOfUniqueMembers objetcClass it give me this exception:

dn: ou=System, ou=Groups, ou=cpt, dc=ccc, dc=net, dc=br
ou: System
objectclass: organizationalUnit
objectclass: top
objectclass: groupOfMembers

Exception in thread "main" org.apache.directory.api.ldap.model.exception.LdapException: ERR_04269 OBJECT_CLASS for OID g
roupofmembers does not exist!

Went to ApacheDS project page and it is supported, what am I missing?

Best regards.

**Comment by kwart** [comment]
Hi, I don't know from where your information about the class comes.

I'm using just the `groupOfNames`. Sth like:

```
dn: cn=Group, ou=Groups, ou=GVT, dc=gvt, dc=net, dc=br
member: cn=Test, ou=GVT, dc=gvt, dc=net, dc=br
cn: Group
objectclass: top
objectclass: groupOfNames
```

**Comment by mjpirez** [comment]
Your example did work, but I needed the groupOfUniqueNames for mocking. Got it working using ApachaDS itself inside eclipse (version >2 I guess).

Thanks anyway!
